### ISSUE TITLE
Quantised model?

### ISSUE THREAD

**Issue by amrrs** [NouamaneTazi/bloomz.cpp#5]
Hey Great Job. Are you also sharing or hosting the quantized model on HF Hub? 

This should help people who just want to 0-shot inference with the default model

**Comment by NouamaneTazi** [comment]
Thanks for the feedback!
That's a great idea! I did upload the [560m model to the hub](https://huggingface.co/nouamanetazi/bloomz-560m-ggml/tree/main). We can try to download the model from there and use it directly for inference.

I also opened [an issue](https://github.com/NouamaneTazi/bloomz.cpp/issues/6) if somebody wants to add a script for that :)

**Comment by amrrs** [comment]
Thank you so much, This is great @NouamaneTazi I'll try to run this tomorrow. For now, will close this issue!
